// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: xrpc.proto

package org.topnetwork.grpclib.xrpc;

public final class HelloWorldProto {
    private HelloWorldProto() {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistryLite registry) {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistry registry) {
        registerAllExtensions(
                (com.google.protobuf.ExtensionRegistryLite) registry);
    }

    static final com.google.protobuf.Descriptors.Descriptor
            internal_static_top_xrpc_request_descriptor;
    static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_top_xrpc_request_fieldAccessorTable;
    static final com.google.protobuf.Descriptors.Descriptor
            internal_static_top_xrpc_reply_descriptor;
    static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_top_xrpc_reply_fieldAccessorTable;

    public static com.google.protobuf.Descriptors.FileDescriptor
    getDescriptor() {
        return descriptor;
    }

    private static com.google.protobuf.Descriptors.FileDescriptor
            descriptor;

    static {
        String[] descriptorData = {
                "\n\nxrpc.proto\022\003top\",\n\014xrpc_request\022\016\n\006act" +
                        "ion\030\001 \001(\t\022\014\n\004body\030\002 \001(\t\"*\n\nxrpc_reply\022\016\n" +
                        "\006result\030\001 \001(\t\022\014\n\004body\030\002 \001(\t2<\n\014xrpc_serv" +
                        "ice\022,\n\004call\022\021.top.xrpc_request\032\017.top.xrp" +
                        "c_reply\"\000B6\n\033io.grpc.examples.helloworld" +
                        "B\017HelloWorldProtoP\001\242\002\003HLWb\006proto3"
        };
        com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
                new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
                    public com.google.protobuf.ExtensionRegistry assignDescriptors(
                            com.google.protobuf.Descriptors.FileDescriptor root) {
                        descriptor = root;
                        return null;
                    }
                };
        com.google.protobuf.Descriptors.FileDescriptor
                .internalBuildGeneratedFileFrom(descriptorData,
                        new com.google.protobuf.Descriptors.FileDescriptor[]{
                        }, assigner);
        internal_static_top_xrpc_request_descriptor =
                getDescriptor().getMessageTypes().get(0);
        internal_static_top_xrpc_request_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_top_xrpc_request_descriptor,
                new String[]{"Action", "Body",});
        internal_static_top_xrpc_reply_descriptor =
                getDescriptor().getMessageTypes().get(1);
        internal_static_top_xrpc_reply_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_top_xrpc_reply_descriptor,
                new String[]{"Result", "Body",});
    }

    // @@protoc_insertion_point(outer_class_scope)
}
