// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: xrpc.proto

package org.topnetwork.grpclib.xrpc;

public interface xrpc_replyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:top.xrpc_reply)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string result = 1;</code>
   */
  String getResult();
  /**
   * <code>string result = 1;</code>
   */
  com.google.protobuf.ByteString
      getResultBytes();

  /**
   * <code>string body = 2;</code>
   */
  String getBody();
  /**
   * <code>string body = 2;</code>
   */
  com.google.protobuf.ByteString
      getBodyBytes();
}
