// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: xrpc.proto

package org.topnetwork.grpclib.xrpc;

public interface xrpc_requestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:top.xrpc_request)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string action = 1;</code>
   */
  String getAction();
  /**
   * <code>string action = 1;</code>
   */
  com.google.protobuf.ByteString
      getActionBytes();

  /**
   * <code>string body = 2;</code>
   */
  String getBody();
  /**
   * <code>string body = 2;</code>
   */
  com.google.protobuf.ByteString
      getBodyBytes();
}
